# Generated by Django 2.0.6 on 2018-06-17 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('liker', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoid', models.IntegerField()),
                ('coords', models.CharField(max_length=20)),
                ('tagged_user', models.CharField(default='', max_length=20)),
                ('tagged_by', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('baseurl', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=20)),
                ('likes', models.IntegerField()),
                ('caption', models.CharField(default='', max_length=140)),
                ('tags', models.IntegerField(default=0)),
                ('main_colour', models.CharField(default='', max_length=15)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
